# 0.001 ; 0.01 ; 0.016
timestep: 0.001

# 60 ; 120 ; 144
fps: 144

# true ; false
true_form: false

# true ; false
auto_shift: true

# true ; false
inverse_steering: true

# Model 7.5 Lateral Scrub (true = dampens drifting, false = raw Model 7 ice physics)
enable_scrub_force: true

# runtime options:
kb_throttle_ramp_engage: 0.5
kb_throttle_ramp_release: 0.2

kb_brake_ramp_engage: 0.5
kb_brake_ramp_release: 0.2

kb_steer_ramp_engage: 0.5
kb_steer_ramp_release: 0.1

# constants preset:
# "DEFAULT"
# "ECONOMY_COMPACT"
# "SPORTS_CAR"
# "TURBO_PERFORMANCE"
# "SUV_TRUCK"
# "ELECTRIC_EV"
# "GO_KART"
# "LIMOUSINE"
# "MCLAREN_P1" (roughly estimated from public sources, very different from the others)
preset: "DEFAULT"